language: node_js
node_js:
  - '8'
cache: yarn
script: # && instead of YAML array, see: https://github.com/travis-ci/travis-ci/issues/1066
  - yarn jest --coverage && node_modules/.bin/codecov && yarn jsdoc && mv out/*/*/* out
deploy:
  provider: surge
  project: ./out/numbered-list
  domain: numbered-list.docs.j4id.com
  skip_cleanup: true
