language: node_js
node_js:
  - '8'
cache: yarn
before_install:
  - yarn global add codecov
script: # && instead of YAML array, see: https://github.com/travis-ci/travis-ci/issues/1066
  - yarn build-prod && yarn jest --coverage && codecov && yarn jsdoc && mkdir -p surge-docs && mv out/*/*/** surge-docs
deploy:
  provider: surge
  project: ./surge-docs
  domain: numbered-list.docs.j4id.com
  skip_cleanup: true
